# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: true
cache: packages
latex: false

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

# Stuff related to V8 package:
# https://github.com/jeroen/V8/blob/master/.travis.yml
addons:
  apt:
    packages:
      - libv8-dev
      - libudunits2-dev
      - gdal-bin
