# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: true
cache: packages
latex: false

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change


# Stuff related to V8 package:
# https://github.com/jeroen/V8/blob/master/.travis.yml
matrix:
  include:
    - r: 3.3
    - r: 3.3
      addons:
        apt:
          sources:
            - sourceline: 'ppa:cran/travis'
          packages: libnode-dev
    - r: release
    - r: release
      addons:
        apt:
          packages: libnode-dev
    - os: osx
      brew_packages: v8
    - os: osx
      before_install:
        - brew install v8@3.15
        - brew link --force v8@3.15
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libv8-dev
